Facturacion/ViewModels/FacturaView.cs
using Data.Entidades;
using Facturacion.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Facturacion.ViewModels
{
    public class FacturaView
    {
        public Cliente  Cliente { get; set; }
        public ProductoFactura ProductoFactura { get; set; }
        public List<ProductoFactura> Productos { get; set; }
    }
}

Facturacion/Controllers/FacturasController.cs
using Data.Contexto;
using Data.Entidades;
using Facturacion.Models;
using Facturacion.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Facturacion.Controllers
{
    [Authorize]
    public class FacturasController : Controller
    {
        Context db = new Context();
        // GET: Facturas
        public ActionResult NuevaFactura()
        {
            var facturaView = new FacturaView();
            facturaView.Cliente = new Cliente();
            facturaView.Productos = new List<ProductoFactura>();
            Session["facturaView"] = facturaView;
            //Crear una lista para ordernarla y armar el ViewBag.Cliente
            var lista = db.Clientes.ToList();
            lista.Add(new Cliente {Id = 0, Nombre="[Seleccione el Cliente]" });
            lista = lista.OrderBy(c => c.Nombre).ToList();
            ViewBag.Cliente = new SelectList(lista, "Id", "Nombre");
            return View(facturaView);
        }

        [HttpPost]
        public ActionResult NuevaFactura(FacturaView facturaView)
        {
            
            facturaView = (FacturaView)Session["facturaView"];
            var ClienteId = int.Parse(Request["Id"]);
            if (ClienteId==0)
            {
                ViewBag.Cliente = new SelectList(db.Clientes.ToList(), "Id", "Nombre");
                ViewBag.Error = "Debe seleccionar un Cliente";
            }
           

            if (facturaView.Productos.Count==0)
            {
                ViewBag.Error = "Factura en blanco";
            }
            var Cliente = db.Clientes.Find(ClienteId);
            if (Cliente==null)
            {
                ViewBag.Cliente = new SelectList(db.Clientes.ToList(), "Id", "Nombre");
                ViewBag.Error = "Este Cliente NO existe";
            }

            var facturaId = 0;
         
            using (var trans = db.Database.BeginTransaction())
            {
                try
                {
                    var factura = new Factura
                    {
                        ClienteId = ClienteId,
                        Fecha = DateTime.Now,

                    };
                    db.Facturas.Add(factura);
                    db.SaveChanges();

                    facturaId = db.Facturas.ToList().Select(f => f.Id).Max();

                    var detalleId = db.Detalles.ToList().Select(d => d.Id).Max();
                    foreach (var item in facturaView.Productos)
                    {
                        var detalle = new Detalle
                        {
                            Id = detalleId,
                            ProductoId = item.Id,
                            Descripcion = item.Descripcion,
                            Cantidad = item.Cantidad,
                            Precio = item.Precio,
                            FacturaId = facturaId

                        };
                        db.Detalles.Add(detalle);
                        db.SaveChanges();                        
                    }
                    trans.Commit();
                }
                catch (Exception ex)
                {
                    trans.Rollback();
                    ViewBag.Error = "No se pudo guardar la orden" + ex;
                    ViewBag.Cliente = new SelectList(db.Clientes.ToList(), "Id", "Nombre");
                    return View(facturaView);
                }
            }
            ViewBag.Mensaje = string.Format("La orden ID: {0} se guardo con exito",facturaId);
            ViewBag.Cliente = new SelectList(db.Clientes.ToList(), "Id", "Nombre");

            //Armo la lista que le voy a pasar
            facturaView = new FacturaView();
            facturaView.Cliente = new Cliente();
            facturaView.Productos = new List<ProductoFactura>();
            Session["facturaView"] = facturaView;
            return View(facturaView);
        }

        public ActionResult AgregarProducto()
        {
            ViewBag.ProductoId = new SelectList(db.Productos.ToList(), "Id", "Descripcion");
            return View();
        }

        [HttpPost]
        public ActionResult AgregarProducto(ProductoFactura productoFactura)
        {
            var productoId = int.Parse(Request["Id"]);
            if (productoId == 0)
            {
                ViewBag.ProductoId = new SelectList(db.Productos.ToList(), "Id", "Descripcion");
                return View(productoFactura);
            }

            //var cantidad = int.Parse(Request["Cantidad"]);
            var producto = db.Productos.Find(productoId);
            var facturaView = (FacturaView)Session["facturaView"];

            productoFactura = facturaView.Productos.Find(p => p.Id==productoId);
            if (productoFactura == null)
            {            
            productoFactura = new ProductoFactura
            {
                Id = producto.Id,
                Descripcion = producto.Descripcion,
                Precio = int.Parse(Request["Precio"]),
                Cantidad = int.Parse(Request["Cantidad"]),
                CategoriaId = producto.CategoriaId,
                Disponible = producto.Disponible
                          
            }; facturaView.Productos.Add(productoFactura);
            }
            else
            {
                productoFactura.Cantidad += int.Parse(Request["Cantidad"]);
            }
          
            ViewBag.Cliente = new SelectList(db.Clientes.ToList(), "Id", "Nombre");
            
            return View("NuevaFactura", facturaView);
        }
    }
}

Facturacion/Views/Facturas/AgregarProducto.cshtml
@model Facturacion.Models.ProductoFactura
@{
    ViewBag.Title = "AgregarProducto";
}

<h2>Agregar Producto</h2>

@using (Html.BeginForm())
{
<div>
    <div>
        <div>@Html.LabelFor(model => model.Id)</div>
        <div>
            @Html.DropDownList("Id", (SelectList)ViewBag.ProductoId, new { @class = "form-control" })
        </div>
    </div>
    <div>
        <div>@Html.LabelFor(model => model.Cantidad)</div>
        <div id="Cantidad">@Html.EditorFor(model => model.Cantidad)</div>
    </div>
    <div>
        <div>@Html.LabelFor(model => model.Precio)</div>
        <div id="Precio">@Html.EditorFor(model => model.Precio)</div>
    </div>
  
</div>
    <input type="submit" name="AgregarProducto" id="Agregar" value="Agregar" />
}
@Html.ActionLink("Regresar sin Agregar","NuevaFactura")

Facturacion/Views/Facturas/NuevaFactura.cshtml
@model Facturacion.ViewModels.FacturaView
@{
    ViewBag.Title = "NuevaFactura";
}
@ViewBag.Error
<h3>@ViewBag.Mensaje</h3>
<h2>Nueva Factura</h2>

@using (Html.BeginForm("NuevaFactura", "Facturas", FormMethod.Post))
{
<div class="form-horizontal">
    <br />
    <div class="row">
        <div class="col-md-2" style="font-style:normal; font-size:larger"> @Html.LabelFor(model => model.Cliente.Nombre)</div>
        <div class="col-md-8">
            @Html.DropDownList("Id", (SelectList)ViewBag.Cliente, new { @class = "form-control" })
        </div>
    </div><br />
    @Html.ActionLink("Agregar Producto", "AgregarProducto", new { }, new { @class = "btn btn-primary" })

</div>
    <br />
        <input type="submit" name="CrearFactura" id="Nueva" value="Guardar Factura" class="btn btn-success" />

}

<h3>Detalle de la Factura</h3>
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.ProductoFactura.Descripcion)</th>
        <th>@Html.DisplayNameFor(model => model.ProductoFactura.Precio)</th>
        <th>@Html.DisplayNameFor(model => model.ProductoFactura.Cantidad)</th>
        <th>@Html.DisplayNameFor(model => model.ProductoFactura.Valor)</th>
    </tr>

    @for (int i = 0; i < Model.Productos.Count; i++)
    {
        <tr>
            <td>@Html.DisplayFor(model => Model.Productos[i].Descripcion)</td>
            <td>@Html.DisplayFor(model => Model.Productos[i].Precio)</td>
            <td>@Html.DisplayFor(model => Model.Productos[i].Cantidad)</td>
            <td>@Html.DisplayFor((model => Model.Productos[i].Valor))</td>
            <td>@Html.ActionLink("Modificar", "Modificar", new { id = Model.Productos[i].Id }) |</td>
            <td>@Html.ActionLink("Quitar", "Eliminar", new { id = Model.Productos[i].Id })</td>
        </tr>
    }
</table>